name: Build Demo and Deploy
on:
  push:
    branches:
      - master

jobs:
  job:
    name: demo-build-deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          wget -q https://github.com/emscripten-core/emsdk/archive/master.tar.gz
          tar -xvf master.tar.gz
          emsdk-master/emsdk update
          emsdk-master/emsdk install latest
          emsdk-master/emsdk activate latest

      - name: Build
        run: |
          pushd emsdk-master
          source ./emsdk_env.sh
          popd
          cd example && make

      - name: Show content of workspace at its completion
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: example/web
