name: Build and Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  job:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          # - os: windows-latest
          #   triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          # - os: macos-latest
          #   triplet: x64-osx

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Build with G++
      - name: Build
        run: |
          g++ test.cpp
      - name: Show content of workspace at its completion
        run: find $RUNNER_WORKSPACE
        shell: bash
