name: Build and Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  job:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          clang++ -Wall -std=c++17 test.cpp -o test

        run: |
          ./test add 2 3 4
