name: Build and Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  job:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest] #, macos-latest, windows-latest]
        include:
          - runs-on: ubuntu-latest
            compiler: gcc
            gcc: 8

    steps:
      - uses: actions/checkout@v2

      # Build with G++
      - name: Build
        run: |
          g++ test.cpp
      - name: Show content of workspace at its completion
        run: find $RUNNER_WORKSPACE
        shell: bash
